// Code generated by protoc-gen-go.
// source: cache.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	cache.proto

It has these top-level messages:
	Entry
	Payload
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Payload struct {
	// Advisory information from owner indicating whether the payload should be
	// cached or not
	ShouldCache bool   `protobuf:"varint,1,opt,name=shouldCache" json:"shouldCache,omitempty"`
	Blob        []byte `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Payload) GetShouldCache() bool {
	if m != nil {
		return m.ShouldCache
	}
	return false
}

func (m *Payload) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "service.Entry")
	proto.RegisterType((*Payload)(nil), "service.Payload")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cache service

type CacheClient interface {
	Get(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Payload, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) Get(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := grpc.Invoke(ctx, "/service.Cache/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cache service

type CacheServer interface {
	Get(context.Context, *Entry) (*Payload, error)
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Cache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Get(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Cache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache.proto",
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4e, 0x4c, 0xce,
	0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
	0x55, 0x32, 0xe7, 0x62, 0x75, 0xcd, 0x2b, 0x29, 0xaa, 0x14, 0x92, 0xe1, 0xe2, 0xcc, 0x4b, 0xcc,
	0x4d, 0x2d, 0x2e, 0x48, 0x4c, 0x4e, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08, 0x08,
	0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x81, 0xc5, 0x41, 0x4c, 0x25, 0x7b, 0x2e, 0xf6,
	0x80, 0xc4, 0xca, 0x9c, 0xfc, 0xc4, 0x14, 0x21, 0x05, 0x2e, 0xee, 0xe2, 0x8c, 0xfc, 0xd2, 0x9c,
	0x14, 0x67, 0x90, 0x0d, 0x60, 0xcd, 0x1c, 0x41, 0xc8, 0x42, 0x42, 0x42, 0x5c, 0x2c, 0x49, 0x39,
	0xf9, 0x49, 0x60, 0xfd, 0x3c, 0x41, 0x60, 0xb6, 0x91, 0x11, 0x17, 0x2b, 0x44, 0x52, 0x93, 0x8b,
	0xd9, 0x3d, 0xb5, 0x44, 0x88, 0x4f, 0x0f, 0xea, 0x26, 0x3d, 0xb0, 0x83, 0xa4, 0x04, 0xe0, 0x7c,
	0xa8, 0x3d, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0xd7, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7c,
	0x3a, 0xc3, 0x2f, 0xcc, 0x00, 0x00, 0x00,
}
